export const sneakers = [
  {
    id: " 1",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    name: "Air Max 90",
    price: 129.99,
    description:
      "The Air Max 90 is a classic shoe that is perfect for any casual occasion.",
    highlights: ["Comfortable fit", "Durable design", "Iconic style"],
    details: {
      material: "Leather and synthetic upper",
      sole: "Rubber",
      closure: "Lace-up",
      origin: "Imported",
    },
    images: [
      "https://example.com/airmax90_1.jpg",
      "https://example.com/airmax90_2.jpg",
      "https://example.com/airmax90_3.jpg",
    ],
  },
  {
    id: "2",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    name: "Chuck Taylor All Star",
    price: 59.99,
    description:
      "The Chuck Taylor All Star is a classic sneaker that never goes out of style.",
    highlights: ["Iconic design", "Versatile", "Easy to clean"],
    details: {
      material: "Canvas upper",
      sole: "Rubber",
      closure: "Lace-up",
      origin: "Imported",
    },
    images: [
      "https://example.com/chucktaylor_1.jpg",
      "https://example.com/chucktaylor_2.jpg",
      "https://example.com/chucktaylor_3.jpg",
    ],
  },
  {
    id: "3",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    name: "Ultra Boost",
    price: 199.99,
    description:
      "The Ultra Boost is a premium running shoe that offers unparalleled comfort and performance.",
    highlights: ["Boost technology", "Flexible design", "Breathable upper"],
    details: {
      material: "Primeknit upper",
      sole: "Rubber",
      closure: "Lace-up",
      origin: "Imported",
    },
    images: [
      "https://example.com/ultraboost_1.jpg",
      "https://example.com/ultraboost_2.jpg",
      "https://example.com/ultraboost_3.jpg",
    ],
  },
  {
    id: "4",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    name: "Classic Leather Sneakers",
    price: 69.99,
    description:
      "'A timeless design with a comfortable fit that's perfect for everyday wear.",
    highlights: ["Leather upper", "EVA midsole", "Rubber outsole"],
    details: {
      material: "Leather upper",
      sole: "EVA midsole and rubber outsole",
      closure: "Lace-up",
      origin: "Imported",
    },
    images: [
      "https://example.com/sneakers1_1.jpg",
      "https://example.com/sneakers1_2.jpg",
      "https://example.com/sneakers1_3.jpg",
    ],
  },
  {
    id: "5",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    name: "Retro High-Top Sneakers",
    price: 79.99,
    description:
      "'A stylish high-top design with a retro look that's sure to turn heads.'",
    highlights: [
      "Synthetic upper",
      "Padded collar and tongue",
      "Rubber outsole",
    ],
    details: {
      material: "Synthetic upper",
      sole: "Rubber outsole",
      closure: "Lace-up",
      origin: "Imported",
    },
    images: [
      "https://example.com/sneakers2_1.jpg",
      "https://example.com/sneakers2_2.jpg",
      "https://example.com/sneakers2_3.jpg",
    ],
  },
  {
    id: "6",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    name: "Running Shoes",
    price: 99.99,
    description:
      "Designed for performance, these running shoes are perfect for athletes of all levels.",
    highlights: [
      "Breathable mesh upper",
      "Responsive cushioning",
      "Durable rubber outsole",
    ],
    details: {
      material: "Mesh upper",
      sole: "Rubber outsole",
      closure: "Lace-up",
      origin: "Imported",
    },
    images: [
      "https://example.com/sneakers3_1.jpg",
      "https://example.com/sneakers3_2.jpg",
      "https://example.com/sneakers3_3.jpg",
    ],
  },
  {
    id: "7",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    name: "Slip-On Sneakers",
    price: 49.99,
    description:
      "Easy to wear and versatile, these slip-on sneakers are a must-have for any casual outfit.",
    highlights: ["Canvas upper", "Elastic side panels", "Rubber outsole"],
    details: {
      material: "Canvas upper",
      sole: "Rubber outsole",
      closure: "Slip-on",
      origin: "Imported",
    },
    images: [
      "https://example.com/sneakers4_1.jpg",
      "https://example.com/sneakers4_2.jpg",
      "https://example.com/sneakers4_3.jpg",
    ],
  },
  {
    id: "8",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    name: "Basketball Shoes",
    price: 129.99,
    description:
      "Designed for the court, these basketball shoes provide the support and traction you need to dominate.",
    highlights: [
      "Leather and mesh upper",
      "Zoom Air cushioning",
      "Rubber outsole",
    ],
    details: {
      material: "Leather and mesh upper",
      sole: "Rubber outsole",
      closure: "Lace-up",
      origin: "Imported",
    },
    images: [
      "https://example.com/sneakers5_1.jpg",
      "https://example.com/sneakers5_2.jpg",
      "https://example.com/sneakers5_3.jpg",
    ],
  },
  {
    id: "9",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    name: "Athletic Training Sneakers",
    price: 89.99,
    description:
      "Ideal for intense training, these sneakers are designed to provide support and stability.",
    highlights: [
      "Breathable mesh upper",
      "Padded collar and tongue",
      "Durable rubber outsole",
    ],
    details: {
      material: "Mesh upper",
      sole: "Rubber outsole",
      closure: "Lace-up",
      origin: "Imported",
    },
    images: [
      "https://example.com/sneakers6_1.jpg",
      "https://example.com/sneakers6_2.jpg",
      "https://example.com/sneakers6_3.jpg",
    ],
  },
  {
    id: "99",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    name: "Skate Shoes",
    price: 59.99,
    description:
      "Designed for skaters, these shoes provide durability and grip for all your tricks.",
    highlights: [
      "Suede and canvas upper",
      "Vulcanized rubber outsole",
      "Padded collar and footbed",
    ],
    details: {
      material: "Suede and canvas upper",
      sole: "Vulcanized rubber outsole",
      closure: "Lace-up",
      origin: "Imported",
    },
    images: [
      "https://example.com/sneakers7_1.jpg",
      "https://example.com/sneakers7_2.jpg",
      "https://example.com/sneakers7_3.jpg",
    ],
  },
  {
    id: "10",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    name: "High-Performance Running Shoes",
    price: 149.99,
    description:
      "Experience ultimate comfort and support with these high-performance running shoes.",
    highlights: [
      "Breathable mesh upper",
      "Responsive cushioning",
      "Durable rubber outsole",
    ],
    details: {
      material: "Mesh upper",
      sole: "Rubber outsole",
      closure: "Lace-up",
      origin: "Imported",
    },
    images: [
      "https://example.com/sneakers8_1.jpg",
      "https://example.com/sneakers8_2.jpg",
      "https://example.com/sneakers8_3.jpg",
    ],
  },
  {
    id: "11",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    name: "Fashion Sneakers",
    price: 79.99,
    description:
      "Make a statement with these trendy fashion sneakers that are perfect for any occasion.",
    highlights: [
      "Synthetic and suede upper",
      "Padded collar and tongue",
      "Rubber outsole",
    ],
    details: {
      material: "Synthetic and suede upper",
      sole: "Rubber outsole",
      closure: "Lace-up",
      origin: "Imported",
    },
    images: [
      "https://example.com/sneakers9_1.jpg",
      "https://example.com/sneakers9_2.jpg",
      "https://example.com/sneakers9_3.jpg",
    ],
  },
  {
    id: "12",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    name: "Classic Leather Sneakers",
    price: 69.99,
    description:
      "A timeless style, these leather sneakers are versatile and comfortable for everyday wear.",
    highlights: [
      "Genuine leather upper",
      "Cushioned footbed",
      "Rubber outsole",
    ],
    details: {
      material: "Leather upper",
      sole: "Rubber outsole",
      closure: "Lace-up",
      origin: "Imported",
    },
    images: [
      "https://example.com/sneakers11_1.jpg",
      "https://example.com/sneakers11_2.jpg",
      "https://example.com/sneakers11_3.jpg",
    ],
  },
  {
    id: "13",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    name: "Minimalist Sneakers",
    price: 49.99,
    description:
      "Keep it simple and stylish with these minimalist sneakers that pair well with any outfit.",
    highlights: ["Canvas upper", "EVA midsole", "Rubber outsole"],
    details: {
      material: "Canvas upper",
      sole: "Rubber outsole",
      closure: "Lace-up",
      origin: "Imported",
    },
    images: [
      "https://example.com/sneakers12_1.jpg",
      "https://example.com/sneakers12_2.jpg",
      "https://example.com/sneakers12_3.jpg",
    ],
  },
  {
    id: "14",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    name: "Basketball Shoes",
    price: 109.99,
    description:
      "Take your game to the next level with these high-performance basketball shoes.",
    highlights: [
      "Synthetic and leather upper",
      "Air cushioning",
      "Durable rubber outsole",
    ],
    details: {
      material: "Synthetic and leather upper",
      sole: "Rubber outsole",
      closure: "Lace-up",
      origin: "Imported",
    },
    images: [
      "https://example.com/sneakers13_1.jpg",
      "https://example.com/sneakers13_2.jpg",
      "https://example.com/sneakers13_3.jpg",
    ],
  },
  {
    id: "15",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    name: "Slip-On Sneakers",
    price: 59.99,
    description:
      "Easy to wear and comfortable, these slip-on sneakers are a great option for casual days.",
    highlights: ["Canvas upper", "Elastic goring", "Padded collar"],
    details: {
      material: "Canvas upper",
      sole: "Rubber outsole",
      closure: "Slip-on",
      origin: "Imported",
    },
    images: [
      "https://example.com/sneakers14_1.jpg",
      "https://example.com/sneakers14_2.jpg",
      "https://example.com/sneakers14_3.jpg",
    ],
  },
  {
    id: "16",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    name: "Hiking Boots",
    price: 139.99,
    description:
      "Designed for rugged terrain, these hiking boots offer durability and support on any trail.",
    highlights: [
      "Waterproof leather upper",
      "Vibram outsole",
      "Gusseted tongue",
    ],
    details: {
      material: "Leather upper",
      sole: "Vibram outsole",
      closure: "Lace-up",
      origin: "Imported",
    },
    images: [
      "https://example.com/sneakers15_1.jpg",
      "https://example.com/sneakers15_2.jpg",
      "https://example.com/sneakers15_3.jpg",
    ],
  },
];
